repos:
#  - repo: https://github.com/psf/black
#    rev: 21.12b0
#    hooks:
#      - id: black
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.10.1
#    hooks:
#      - id: isort
#  - repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: 'v1.5.7'  
#    hooks:
#  - id: autopep8
#  - repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
   - repo: https://github.com/sqlfluff/sqlfluff
     rev: 0.8.2
     hooks:
       - id: sqlfluff-lint
         args: [--dialect=hive]
       - id: sqlfluff-fix
         args: [--dialect=hive]
         # Arbitrary arguments to show an example
         # args: [--rules, "L003,L014"]
         # additional_dependencies: ['.[dbt]']
#
#
